//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgendaVirtual.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Agenda
    {
        public int Id_Anotacao { get; set; }
        public string Anotacao { get; set; }
        public string DataAnotacao { get; set; }
    }
}
