//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Academico
    {
        public int Id_Academico { get; set; }
        public string Nome { get; set; }
        public string Sexo { get; set; }
        public string Idade { get; set; }
        public bool Excluido { get; set; }
        public bool Ativo { get; set; }
    }
}
