//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nota
    {
        public int Id_Nota { get; set; }
        public int Id_Academico { get; set; }
        public string Nome_Materia { get; set; }
        public decimal Nota_I { get; set; }
        public decimal Nota_II { get; set; }
        public decimal Nota_III { get; set; }
        public decimal Nota_IV { get; set; }
    
        public virtual Academico Academico { get; set; }
    }
}
